# Generated by Django 4.2.7 on 2023-11-12 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome do Artista', max_length=100)),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=100, verbose_name='Sexo')),
                ('foto', models.ImageField(upload_to='artistas', verbose_name='Foto')),
                ('bio', models.TextField(verbose_name='Biografia')),
                ('indicacoes_oscar', models.IntegerField(default=0, verbose_name='Indicações ao OSCAR')),
                ('premios_oscar', models.IntegerField(default=0, verbose_name='Premiações do OSCAR')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('foto', models.ImageField(upload_to='poster', verbose_name='Foto')),
                ('genero', models.CharField(choices=[('Comédia', 'Comédia'), ('Ficção', 'Ficção'), ('Suspense', 'Suspense'), ('Aventura', 'Aventura'), ('Romance', 'Romance'), ('Animação', 'Animação'), ('Drama', 'Drama'), ('Policial', 'Policial')], max_length=255, verbose_name='Gênero')),
                ('estudios', models.CharField(max_length=100, verbose_name='Estúdio de Produção')),
                ('tipo', models.CharField(choices=[('Filme', 'Filme'), ('Série', 'Série')], max_length=255, verbose_name='Formato')),
                ('volumes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Filmes')),
                ('temporada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Temporadas')),
                ('episodios', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Episódios')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Nerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome do Personagem', max_length=100)),
                ('profissao', models.CharField(default='Profissão do Personagem', max_length=100)),
                ('sobre', models.TextField(default='Sobre o personagem', max_length=900)),
                ('foto', models.ImageField(default='default_capa.jpg', upload_to='avatar')),
                ('interprete', models.ManyToManyField(to='personas.artista', verbose_name='Interpretes')),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.midia', verbose_name='Mídia')),
            ],
            options={
                'verbose_name': 'Nerd',
                'verbose_name_plural': 'Nerds',
                'ordering': ['nome'],
            },
        ),
    ]
